<a href="https://colab.research.google.com/github/Hunny-Chaurasia/DATA_SCIENCE/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Module



In [758]:
import numpy as np

1. Array Creation Methods

*np.array(): Converts standard Python iterables (like lists or tuples) into an N-dimensional array (ndarray).*

In [759]:
arr1=np.array((1,2,3,4,5))
arr2=np.array([1,2,3,4,5])
print(arr1 ,"\n", arr2)

[1 2 3 4 5] 
 [1 2 3 4 5]


*np.arange(start, stop, step): Generates sequential numerical values over a specified interval (similar to Python's built-in range).*

In [760]:
arr1= np.arange(9, 900, 10)
arr2= np.arange(9)
print(arr1 ,"\n\n\n", arr2)

[  9  19  29  39  49  59  69  79  89  99 109 119 129 139 149 159 169 179
 189 199 209 219 229 239 249 259 269 279 289 299 309 319 329 339 349 359
 369 379 389 399 409 419 429 439 449 459 469 479 489 499 509 519 529 539
 549 559 569 579 589 599 609 619 629 639 649 659 669 679 689 699 709 719
 729 739 749 759 769 779 789 799 809 819 829 839 849 859 869 879 889 899] 


 [0 1 2 3 4 5 6 7 8]


*np.zeros(shape): Creates an array filled entirely with zeros of a specified size/dimension.*

In [761]:
arr1=np.zeros((3,5))
arr2=np.zeros(3)
print(arr1 ,"\n\n\n", arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 


 [0. 0. 0.]


*np.ones(shape): Creates an array filled entirely with ones.*

In [762]:
arr1=np.ones((3,5))
arr2=np.ones(3)
print(arr1 ,"\n\n\n", arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 


 [1. 1. 1.]


*np.linspace(start, stop, num): Generates evenly spaced numbers over a specified mathematical interval.*

In [763]:
arr1=np.linspace(9, 900, 9)
arr2=np.linspace(9, 900, 9, dtype=int)
print(arr1 ,"\n\n\n", arr2)

[  9.    120.375 231.75  343.125 454.5   565.875 677.25  788.625 900.   ] 


 [  9 120 231 343 454 565 677 788 900]


*np.copy(array): Creates a completely independent copy of an existing array in memory (so modifying the copy won't accidentally change your original data).*


In [764]:
arr2=np.copy(arr1)
print(arr2)

[  9.    120.375 231.75  343.125 454.5   565.875 677.25  788.625 900.   ]


*np.full(shape, fill_value) : Fills an array entirely with a custom static number of your choice.*


In [765]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

*np.empty(shape) : Allocates memory for an array without initializing its values. It contains whatever random "garbage values" were left over in your computer's RAM.*

In [766]:
np.empty((2,3))

array([[5.        , 0.2       , 1.66666667],
       [1.66666667, 0.6       , 1.        ]])

*np.eye(N) : What it does: Creates a square Identity Matrix of size $N \times N$, where the diagonal values are 1 and all other entries are 0.*

In [767]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [768]:
original_data = np.random.rand(4, 5, 2)
original_data

array([[[0.19496895, 0.65669438],
        [0.83882512, 0.59239576],
        [0.05296435, 0.87506584],
        [0.79397448, 0.49297727],
        [0.29555965, 0.12170013]],

       [[0.05112373, 0.92760344],
        [0.06518359, 0.05872712],
        [0.66713081, 0.81939107],
        [0.95658493, 0.09955204],
        [0.95085238, 0.85668118]],

       [[0.66046009, 0.04040916],
        [0.44959825, 0.56810496],
        [0.65645094, 0.61246983],
        [0.87872622, 0.30778305],
        [0.23621487, 0.24873165]],

       [[0.88699043, 0.94025489],
        [0.44779381, 0.21125897],
        [0.40856701, 0.39131504],
        [0.97354118, 0.92379372],
        [0.52836923, 0.56981146]]])

In [769]:
import numpy as np

# Imagine this is a 3D dataset: e.g., 4 frames, 5 pixels high, 2 channels wide
original_data = np.random.rand(4, 5, 2)
print("Original Shape:", original_data.shape)
# Output: (4, 5, 2)

# --- Creating the Clones ---

# 1. A blank mask matching the exact size, filled with zeros
zero_mask = np.zeros_like(original_data)

# 2. A baseline multiplier matching the exact size, filled with ones
ones_multiplier = np.ones_like(original_data)

# 3. A bias matrix matching the exact size, filled with a specific value (e.g., -1)
bias_matrix = np.full_like(original_data, -1.0)

# Verification
print("Zero Clone Shape:", zero_mask)        # Output: (4, 5, 2)
print("Bias Clone Shape:", bias_matrix)      # Output: (4, 5, 2)
print("First element of bias:", ones_multiplier) # Output: -1.0

Original Shape: (4, 5, 2)
Zero Clone Shape: [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
Bias Clone Shape: [[[-1. -1.]
  [-1. -1.]
  [-1. -1.]
  [-1. -1.]
  [-1. -1.]]

 [[-1. -1.]
  [-1. -1.]
  [-1. -1.]
  [-1. -1.]
  [-1. -1.]]

 [[-1. -1.]
  [-1. -1.]
  [-1. -1.]
  [-1. -1.]
  [-1. -1.]]

 [[-1. -1.]
  [-1. -1.]
  [-1. -1.]
  [-1. -1.]
  [-1. -1.]]]
First element of bias: [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [770]:
import numpy as np

# Imagine this is a 3D dataset: e.g., 4 frames, 5 pixels high, 2 channels wide
original_data = np.random.rand(4, 5, 2)
print("Original Shape:", original_data.shape)
# Output: (4, 5, 2)

# --- Creating the Clones ---

# 1. A blank mask matching the exact size, filled with zeros
zero_mask = np.zeros_like(original_data)

# 2. A baseline multiplier matching the exact size, filled with ones
ones_multiplier = np.ones_like(original_data)

# 3. A bias matrix matching the exact size, filled with a specific value (e.g., -1)
bias_matrix = np.full_like(original_data, -1.0)

# Verification
print("Zero Clone Shape:", zero_mask.shape)        # Output: (4, 5, 2)
print("Bias Clone Shape:", bias_matrix.shape)      # Output: (4, 5, 2)
print("First element of bias:", bias_matrix[0,0,0]) # Output: -1.0

Original Shape: (4, 5, 2)
Zero Clone Shape: (4, 5, 2)
Bias Clone Shape: (4, 5, 2)
First element of bias: -1.0


**2. Array Inspection & Structural Attributes**

*.shape: Returns a tuple representing the dimensions of the array (e.g., (rows, columns)).*

In [771]:
arr1=np.array([[1,2],[2,3],[3,4]])
arr1.shape

(3, 2)

*.ndim: Returns the number of array dimensions (axes).*

In [772]:
arr1.ndim

2

*.dtype: Outputs the specific data type stored within the array elements (e.g., int32, float64).*

In [773]:
arr1.dtype

dtype('int64')

**3. Shape Manipulation Methods**

*.reshape(new_shape): Changes the structural dimensions of an array without changing its underlying data (e.g., turning a 1D array of 12 elements into a 2D $3 \times 4$ matrix).*

In [774]:
flat_array = np.arange(12)
print(flat_array)
reshaped_array = flat_array.reshape((3, 4))
print(reshaped_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


*reshape() : when the number of a row or column we need in reshaped array is unknown*

In [775]:
flat_array.reshape((2, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [776]:
flat_array.reshape((-1 ,4)) #it can be any negative number

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

*.base :  to see the original array as well after reshaping.*

In [777]:
flat_array.reshape((-1 ,4)).base

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**4. Indexing & Slicing Mechanics**

*Multi-dimensional Slicing: Syntax like array[row_start:row_end, col_start:col_end] to extract specific subsections of a matrix.*

In [778]:
print("a",reshaped_array[1:3, 1:3],"\n")
print("b",reshaped_array[1:3, 2:3],"\n")
print("c",reshaped_array[2:3, 1:3],"\n")
print("d",reshaped_array[:3, 1:3],"\n")

a [[ 5  6]
 [ 9 10]] 

b [[ 6]
 [10]] 

c [[ 9 10]] 

d [[ 1  2]
 [ 5  6]
 [ 9 10]] 



*Boolean Indexing (Filtering): Passing a conditional statement inside the index brackets to extract values that match a criteria (e.g., arr[arr > 5]).*

In [779]:
flat_array[flat_array > 5]

array([ 6,  7,  8,  9, 10, 11])

In [780]:
np.where(flat_array > 5)

(array([ 6,  7,  8,  9, 10, 11]),)

In [781]:
np.extract(flat_array>3,flat_array)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

**5. Random Sampling Module (np.random)**

*np.random.randint(low, high, size): Generates random integers within a specific range.*

In [782]:
dice_rolls = np.random.randint(1, 7, size=5)
print("Dice Rolls:", dice_rolls)

Dice Rolls: [3 3 2 6 6]


In [783]:
dice_rolls = np.random.randint(1, 7)
print("Dice Rolls:", dice_rolls)

Dice Rolls: 1


In [784]:
dice_rolls = np.random.randint(1, 7,5 )
print("Dice Rolls:", dice_rolls)

Dice Rolls: [3 2 3 5 2]


In [785]:
dice_rolls = np.random.randint( 7, size=5)
print("Dice Rolls:", dice_rolls)

Dice Rolls: [5 1 5 1 4]


In [786]:
dice_rolls = np.random.randint(6, 7, size=5)
print("Dice Rolls:", dice_rolls)

Dice Rolls: [6 6 6 6 6]


*np.random.randn(size): Generates random floats following a standard normal distribution.*

In [787]:
np.random.randn(4)

array([0.28418166, 0.09569534, 0.31474079, 0.70697278])

*np.random.binomial(n, p, size): Simulates discrete outcomes based on success/failure probability over a set number of trials.(Counts successes in a series of yes/no trials (like flipping coins).)*

In [788]:
np.random.binomial(n=10, p=0.5, size=3)

array([5, 0, 5])

In [789]:
np.random.binomial(n=10, p=0.5, size=300)

array([4, 5, 2, 4, 7, 1, 6, 3, 3, 2, 3, 5, 6, 3, 6, 5, 6, 4, 5, 5, 5, 6,
       5, 4, 6, 4, 7, 7, 4, 7, 3, 7, 7, 4, 6, 4, 8, 3, 5, 3, 6, 4, 4, 4,
       6, 3, 5, 5, 4, 3, 8, 4, 3, 4, 4, 4, 5, 3, 7, 4, 5, 3, 8, 5, 5, 8,
       4, 7, 5, 3, 6, 5, 8, 5, 4, 3, 3, 4, 4, 3, 6, 4, 0, 7, 7, 6, 7, 4,
       5, 6, 7, 5, 2, 5, 5, 2, 6, 6, 5, 4, 6, 4, 5, 5, 5, 6, 4, 4, 5, 5,
       4, 4, 2, 3, 5, 5, 5, 3, 9, 5, 5, 4, 7, 4, 6, 9, 7, 6, 3, 4, 5, 6,
       5, 8, 6, 5, 1, 3, 4, 7, 3, 6, 2, 3, 6, 7, 4, 4, 3, 5, 5, 5, 5, 3,
       7, 6, 5, 4, 4, 6, 3, 3, 5, 5, 2, 5, 4, 5, 3, 4, 6, 3, 5, 6, 5, 4,
       6, 2, 4, 5, 8, 5, 6, 5, 6, 5, 4, 6, 3, 4, 6, 4, 7, 5, 5, 4, 5, 5,
       5, 3, 8, 6, 7, 7, 5, 3, 6, 5, 7, 5, 4, 2, 7, 5, 4, 6, 7, 6, 5, 4,
       3, 9, 6, 5, 5, 5, 6, 5, 5, 7, 6, 4, 7, 2, 6, 3, 6, 4, 4, 7, 4, 5,
       6, 6, 8, 8, 5, 6, 4, 8, 3, 6, 6, 4, 7, 4, 6, 6, 5, 6, 6, 4, 5, 7,
       3, 5, 4, 3, 3, 6, 7, 7, 8, 6, 5, 6, 2, 7, 7, 7, 4, 3, 3, 7, 5, 5,
       3, 2, 7, 5, 7, 7, 3, 8, 5, 6, 3, 4, 5, 8])

# Numpy 2

**1. Conditions on array**

In [790]:
arr1=np.random.randint(1,6,(2,3))
arr1


array([[5, 4, 2],
       [5, 3, 3]])

In [791]:
arr1>3

array([[ True,  True, False],
       [ True, False, False]])

In [792]:
arr1[0]>3

array([ True,  True, False])

In [793]:
#To filter columns where the top row is > 3: You need to add a comma to slice across columns:
arr1[:, arr1[0] > 3]

array([[5, 4],
       [5, 3]])

In [794]:
#To filter rows based on the first column being > 3:
arr1[arr1[:, 0] > 3]

array([[5, 4, 2],
       [5, 3, 3]])

**2. Mathematical operations on two arrays**

In [795]:
arr1=np.random.randint(1,6,(2,3))
arr2=np.random.randint(1,6,(2,3))

*Indexwise element matrix Addition*

In [796]:
arr1+arr2

array([[ 5,  4,  7],
       [10,  7,  6]])

*Indexwise element matrix Substraction*

In [797]:
arr1-arr2

array([[-1,  2, -1],
       [ 0,  1,  0]])

*Indexwise element matrix Multiplication*

In [798]:
arr1*arr2

array([[ 6,  3, 12],
       [25, 12,  9]])

In [799]:
arr1=np.random.randint(1,6,(2,3))
arr2=np.random.randint(1,6,(2,3))
np.multiply(arr1,arr2)

array([[12,  2,  1],
       [12,  3,  2]])

*Indexwise element matrix Division*

In [800]:
arr1/arr2

array([[1.33333333, 0.5       , 1.        ],
       [1.33333333, 0.33333333, 0.5       ]])

*dot product for 2D arrays and matrix multiplication*

In [801]:
arr1@arr2.T

array([[15, 17],
       [15, 17]])

In [802]:
np.dot(arr1,arr2.T)

array([[15, 17],
       [15, 17]])

**3. Broadcasting / Scalar Operations**

In [803]:
arr1+10

array([[14, 11, 11],
       [14, 11, 11]])

In [804]:
arr1 - 2

array([[ 2, -1, -1],
       [ 2, -1, -1]])

In [805]:
arr1 * 2

array([[8, 2, 2],
       [8, 2, 2]])

In [806]:
arr1 / 2

array([[2. , 0.5, 0.5],
       [2. , 0.5, 0.5]])

In [807]:
arr1 // 2

array([[2, 0, 0],
       [2, 0, 0]])

In [808]:
arr1 % 2

array([[0, 1, 1],
       [0, 1, 1]])

In [809]:
arr1 ** 2

array([[16,  1,  1],
       [16,  1,  1]])

**4. Transpose**

In [810]:
print(arr1)

[[4 1 1]
 [4 1 1]]


In [811]:
print(arr1.T)

[[4 4]
 [1 1]
 [1 1]]


**5. Other Mathematical Functions.**

*Roots, Powers, and Exponentials*

In [812]:
np.sqrt(arr1)

array([[2., 1., 1.],
       [2., 1., 1.]])

In [813]:
np.square(arr1)

array([[16,  1,  1],
       [16,  1,  1]])

In [814]:
np.reciprocal(arr1)

array([[0, 1, 1],
       [0, 1, 1]])

In [815]:
np.cbrt(arr1) #Cube Root

array([[1.58740105, 1.        , 1.        ],
       [1.58740105, 1.        , 1.        ]])

In [816]:
np.exp(arr1) #exponential

array([[54.59815003,  2.71828183,  2.71828183],
       [54.59815003,  2.71828183,  2.71828183]])

In [817]:
np.power(arr1, 3)

array([[64,  1,  1],
       [64,  1,  1]])

*Logarithmic Functions : Used extensively in data scaling and machine learning loss functions.
(Note: These will return nan or -inf if given negative numbers or zero)*

*np.log(arr): Natural logarithm (base $e$)*

In [818]:
np.log(arr1)

array([[1.38629436, 0.        , 0.        ],
       [1.38629436, 0.        , 0.        ]])

In [819]:
np.log10(arr1)

array([[0.60205999, 0.        , 0.        ],
       [0.60205999, 0.        , 0.        ]])

In [820]:
np.log2(arr1)

array([[2., 0., 0.],
       [2., 0., 0.]])

*Calculates $\ln(1 + x)$. This is highly useful for handling zero values safely.*

In [821]:
np.log1p(arr1)

array([[1.60943791, 0.69314718, 0.69314718],
       [1.60943791, 0.69314718, 0.69314718]])

**3. Absolute Values and Signs**

*Removes any negative signs, returning the absolute magnitude.*

In [822]:
np.abs(arr1)

array([[4, 1, 1],
       [4, 1, 1]])

In [823]:
np.absolute(arr1)

array([[4, 1, 1],
       [4, 1, 1]])

*np.sign(arr): Returns -1 for negative numbers, 0 for zero, and 1 for positive numbers.*

In [824]:
np.sign(arr1)

array([[1, 1, 1],
       [1, 1, 1]])

**4. Trigonometric Functions**

*Standard*

In [825]:
print(np.sin(arr1),"\n\n\n", np.cos(arr1),"\n\n\n", np.tan(arr1))

[[-0.7568025   0.84147098  0.84147098]
 [-0.7568025   0.84147098  0.84147098]] 


 [[-0.65364362  0.54030231  0.54030231]
 [-0.65364362  0.54030231  0.54030231]] 


 [[1.15782128 1.55740772 1.55740772]
 [1.15782128 1.55740772 1.55740772]]


*Inverse*

In [826]:
print(np.arcsin(arr1),"\n\n\n", np.arccos(arr1),"\n\n\n", np.arctan(arr1))

[[       nan 1.57079633 1.57079633]
 [       nan 1.57079633 1.57079633]] 


 [[nan  0.  0.]
 [nan  0.  0.]] 


 [[1.32581766 0.78539816 0.78539816]
 [1.32581766 0.78539816 0.78539816]]


/tmp/ipykernel_710/2986316738.py:1: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(arr1),"\n\n\n", np.arccos(arr1),"\n\n\n", np.arctan(arr1))
/tmp/ipykernel_710/2986316738.py:1: RuntimeWarning: invalid value encountered in arccos
  print(np.arcsin(arr1),"\n\n\n", np.arccos(arr1),"\n\n\n", np.arctan(arr1))


*Hyperbolic*

In [827]:
print(np.sinh(arr1),"\n\n\n",  np.cosh(arr1),"\n\n\n",  np.tanh(arr1))

[[27.2899172   1.17520119  1.17520119]
 [27.2899172   1.17520119  1.17520119]] 


 [[27.30823284  1.54308063  1.54308063]
 [27.30823284  1.54308063  1.54308063]] 


 [[0.9993293  0.76159416 0.76159416]
 [0.9993293  0.76159416 0.76159416]]


*Degrees conversion:*

(radians to degrees)

In [828]:
np.degrees(arr1)

array([[229.18311805,  57.29577951,  57.29577951],
       [229.18311805,  57.29577951,  57.29577951]])

(degrees to radians)

In [829]:
np.radians(arr1)

array([[0.06981317, 0.01745329, 0.01745329],
       [0.06981317, 0.01745329, 0.01745329]])

**5. Rounding and Truncation**

*np.ceil(arr): Rounds up to the nearest integer.*

In [830]:
np.ceil(arr1)

array([[4., 1., 1.],
       [4., 1., 1.]])

*np.floor(arr1) : Rounds down to the nearest integer.*

In [831]:
np.floor(arr1)

array([[4., 1., 1.],
       [4., 1., 1.]])

*np.trunc(arr): Discards the decimal part entirely (rounds toward zero)*

In [832]:
np.trunc(arr1)

array([[4., 1., 1.],
       [4., 1., 1.]])

*np.round(arr, decimals=0): Standard rounding to the nearest even number or specified decimal place.*

In [833]:
np.round(arr1, decimals=0)

array([[4, 1, 1],
       [4, 1, 1]])

# Numpy - 3

**1. Flattening Arrays**

*arr1.flatten(): As seen in cell [4], this method collapses a multi-dimensional array down into a single dimension (1D). It returns a copy of the original data.*

In [834]:
arr1.flatten()

array([4, 1, 1, 4, 1, 1])

**2. Expand Array's Dimension**

*np.expand_dims() : add a new dimension (axis) to an array:*

In [835]:
arr=np.array([1,2,3,4,5 , 6,7,8,9,1,2,3])

In [836]:
np.expand_dims(arr , axis=0)#y axis

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3]])

In [837]:
np.expand_dims(arr , axis=0).ndim

2

In [838]:
np.expand_dims(arr , axis=1) #x axis

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [1],
       [2],
       [3]])

In [839]:
np.expand_dims(arr , axis=1).ndim

2

In [840]:
arr=np.array([[1,2,3,4,5],[ 6,7,8,9,1]])

In [841]:
np.expand_dims(arr , axis=0).ndim

3

In [842]:
np.expand_dims(arr , axis=0)

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 1]]])

**2. Squeeze an array**

*np.squeeze() : (often called a "singleton dimension"), and drops it, flattening that specific axis out*

In [843]:
arr=np.array([[1,2,3,4,5],[ 6,7,8,9,1]])
np.squeeze(arr)


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [844]:
arr=np.array([[1,2,3,4,5],[ 6,7,8,9,1]])
np.squeeze(arr, axis=0)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [845]:
arr2 = np.array([[1, 2, 3, 4, 5]])
np.squeeze(arr2, axis=0)

array([1, 2, 3, 4, 5])

**3. Repeating elements**

*The np.repeat() function repeats elements of an array a specified number of times along a given axis.*

In [846]:
arr=np.array([[1,5],[ 6,7]])
np.repeat(arr, 4)

array([1, 1, 1, 1, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7])

*Repeating Along Rows: np.repeat(a, 4, axis=0)
If you specify axis=0, you are telling NumPy to repeat the rows 4 times.*

In [847]:
np.repeat(arr, 2, axis=0)

array([[1, 5],
       [1, 5],
       [6, 7],
       [6, 7]])

*Repeating Along Columns: np.repeat(a, 4, axis=1)
If you specify axis=1, you are telling NumPy to repeat the columns 4 times.*

In [848]:
np.repeat(arr, 2, axis=1)

array([[1, 1, 5, 5],
       [6, 6, 7, 7]])

**4. Roll the Matrix**

*np.roll(). This function shifts (rotates) elements of an array along a specified axis. When elements are pushed off the end of an axis, they wrap around ("roll") to the beginning.*

In [849]:
arr

array([[1, 5],
       [6, 7]])

In [850]:
np.roll(arr,1)

array([[7, 1],
       [5, 6]])

In [851]:
np.roll(arr,2)

array([[6, 7],
       [1, 5]])

In [852]:
np.roll(arr,3)

array([[5, 6],
       [7, 1]])

In [853]:
np.roll(arr,-1)

array([[5, 6],
       [7, 1]])

*np.roll(a, shift=1, axis=0) : Shift by +1 (Move down by 1):*

In [854]:
arr=np.array([[1,2],[3,4],[5,6]])

In [855]:
np.roll(arr, shift=1, axis=0)

array([[5, 6],
       [1, 2],
       [3, 4]])

In [856]:
arr=np.array([[1,2],[3,4],[5,6]])

In [857]:
np.roll(arr, shift=1, axis=1)

array([[2, 1],
       [4, 3],
       [6, 5]])

*Shift by -1 (Move up by 1):*

In [858]:
np.roll(arr, shift=-1, axis=1)

array([[2, 1],
       [4, 3],
       [6, 5]])

*.byteswap(), NumPy literally flips the low and high bytes of the data representation in memory:*

In [859]:
arr.byteswap()

array([[ 72057594037927936, 144115188075855872],
       [216172782113783808, 288230376151711744],
       [360287970189639680, 432345564227567616]])

# Numpy String Array

In [860]:
d = np.array(["Pw ", " skills"])
d

array(['Pw ', ' skills'], dtype='<U7')

In [861]:
np.char.upper(d)

array(['PW ', ' SKILLS'], dtype='<U7')

In [862]:
np.char.capitalize(d)

array(['Pw ', ' skills'], dtype='<U7')

In [863]:
np.char.title(d)

array(['Pw ', ' Skills'], dtype='<U7')

In [864]:
np.char.swapcase(d)

array(['pW ', ' SKILLS'], dtype='<U7')

In [865]:
np.char.isnumeric(d)

array([False, False])

In [866]:
np.char.isalnum(d)

array([False, False])

In [867]:
np.char.isalpha(d)

array([False, False])

In [868]:
np.char.lower(d)

array(['pw ', ' skills'], dtype='<U7')

In [869]:
np.char.upper(d)

array(['PW ', ' SKILLS'], dtype='<U7')

*sort*

In [870]:
np.sort(arr2)

array([[1, 2, 3, 4, 5]])

In [871]:
np.searchsorted(arr2.flatten(),2)

np.int64(1)

In [872]:
arr=np.array([1,2,3,0,4,0,6,0,6,0])

In [873]:
np.count_nonzero(arr)

6

# Linear Algebra in Numpy

In [876]:
A=np.array([[1,2,5],[2,4,6],[1,7,5]])
b=np.array([3,4,5])

**1. Matrix Inversion & Solving Systems**

*np.linalg.inv(A): Computes the multiplicative inverse of a square matrix ($A^{-1}$).*

In [877]:
np.linalg.inv(A)

array([[-1.1 ,  1.25, -0.4 ],
       [-0.2 ,  0.  ,  0.2 ],
       [ 0.5 , -0.25,  0.  ]])

*np.linalg.solve(A, b): Computes the exact solution vector $x$ for the linear equation $Ax = b$ (more computationally stable and faster than manually doing inv(A) @ b).*

In [878]:
np.linalg.solve(A, b)

array([-0.3,  0.4,  0.5])

*np.linalg.pinv(A): Computes the Moore-Penrose pseudo-inverse for non-square matrices.*

In [879]:
np.linalg.pinv(A)

array([[-1.10000000e+00,  1.25000000e+00, -4.00000000e-01],
       [-2.00000000e-01, -2.45569092e-16,  2.00000000e-01],
       [ 5.00000000e-01, -2.50000000e-01, -2.39337508e-16]])

**2. Matrix Decomposition**(Factorization)
Decomposing a matrix into fundamental components is a key step in machine learning algorithms like PCA (Principal Component Analysis) and recommendation systems.

**3. Matrix Properties & Statistics**
Functions that summarize the structural characteristics of a matrix.

*np.linalg.det(A): Calculates the determinant of a matrix, which measures the scaling factor of the transformation.*

In [880]:
np.linalg.det(A)

np.float64(19.999999999999996)